config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'sessions/create'

  resources :users
  get 'showcustomerboxes/customernamein'
  get 'showcustomerboxes/boxesout'
  post 'showcustomerboxes/boxesout'
  post 'showcustomerboxes/customernamein'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :subscriptions
  resources :customers
  get 'maintenance/maintview'

  get 'boxout/outbox'

  root :to => 'starter#home' 

  resources :boxes

end

app/models/box.rb
class Box < ActiveRecord::Base
    has_many :subscriptions
  has_many :customers, :through => :subscriptions
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :content, :price)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<script src="../_js/jquery-1.7.2.min.js"></script>
<script>
$(document).ready(function() { 
outtoConfirm = function()
{
$('body').css('background-color','#ccbadc');

$('h1').after('<center> <h2> Check all data. Make changes if necessary. Then hit the <b>"Submit"</b> button </h2></center>');
var titlein, contentin, pricein; 
titlein = $('#box_title').val();
contentin = $('#box_content').val();
pricein= $('#box_price').val();

$('#box_title').css('background-color', 'yellow');
$('#box_title').val(titlein);
$('#box_content').css('background-color', 'yellow');
$('#box_content').val(contentin); 
$('#box_price').css('background-color', 'yellow');
$('#box_price').val(pricein);
$('#box_price').after('<p><input name="submitButton" type="submit" id="submission" value="Submit Confirmed Data" length = 20> </p>');
$('#confirmButton').remove();
$('#submission').hover(function()
{ 
$(this).css('background-color', '#ccbadc') 


}); //end 
}
$('#confirmButton').click(outtoConfirm); 
}); //end ready
</script>


</script>
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <input name="submitButton" type="submit" id="confirmButton" value="Submit Data" length = 20> </p>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.title %></td>
        <td><%= box.content %></td>
        <td><%= box.price %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @box.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @box.content %>
</p>

<p>
  <strong>Price:</strong>
  <%= @box.price %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>